export interface FrameworkPreset {
  id: string;
  name: string;
  icon: string;
  category: "node" | "python" | "docker" | "static" | "other";
  description: string;
  defaultRootDirectory: string;
  installCommand: string;
  buildCommand: string;
  startCommand: string;
  defaultPort: number;
  healthCheckUrl: string;
  processManager: "node" | "pm2" | "docker-compose" | "docker" | "python" | "custom";
}

export const FRAMEWORK_PRESETS: FrameworkPreset[] = [
  {
    id: "vite",
    name: "Vite (React / Vue / Svelte)",
    icon: "⚡",
    category: "node",
    description: "Vite SPA frontend with preview or static serve",
    defaultRootDirectory: "frontend",
    installCommand: "npm install",
    buildCommand: "npm run build",
    startCommand: "npx serve -s dist -l 3000",
    defaultPort: 3000,
    healthCheckUrl: "/",
    processManager: "node",
  },
  {
    id: "nextjs",
    name: "Next.js",
    icon: "▲",
    category: "node",
    description: "Next.js fullstack React application",
    defaultRootDirectory: "",
    installCommand: "npm install",
    buildCommand: "npm run build",
    startCommand: "npx next start -H 0.0.0.0 -p 3000",
    defaultPort: 3000,
    healthCheckUrl: "/",
    processManager: "node",
  },
  {
    id: "fastapi",
    name: "Python (FastAPI / Uvicorn)",
    icon: "⚡",
    category: "python",
    description: "High-performance Python FastAPI async backend",
    defaultRootDirectory: "backend",
    installCommand: "pip install -r requirements.txt",
    buildCommand: "",
    startCommand: "python -m uvicorn app.main:app --host 0.0.0.0 --port 8000",
    defaultPort: 8000,
    healthCheckUrl: "/docs",
    processManager: "python",
  },
  {
    id: "flask",
    name: "Python (Flask / Gunicorn)",
    icon: "🌶️",
    category: "python",
    description: "Flask web server running with Gunicorn",
    defaultRootDirectory: "backend",
    installCommand: "pip install -r requirements.txt",
    buildCommand: "",
    startCommand: "gunicorn -w 4 -b 0.0.0.0:5000 app:app",
    defaultPort: 5000,
    healthCheckUrl: "/",
    processManager: "python",
  },
  {
    id: "django",
    name: "Python (Django)",
    icon: "🎸",
    category: "python",
    description: "Django web framework with Gunicorn and static collection",
    defaultRootDirectory: "",
    installCommand: "pip install -r requirements.txt",
    buildCommand: "python manage.py migrate --noinput && python manage.py collectstatic --noinput",
    startCommand: "gunicorn --bind 0.0.0.0:8000 project.wsgi:application",
    defaultPort: 8000,
    healthCheckUrl: "/",
    processManager: "python",
  },
  {
    id: "express",
    name: "Node.js (Express / NestJS / Fastify)",
    icon: "🟢",
    category: "node",
    description: "Node.js backend API or server",
    defaultRootDirectory: "",
    installCommand: "npm install",
    buildCommand: "npm run build",
    startCommand: "node index.js",
    defaultPort: 3000,
    healthCheckUrl: "/",
    processManager: "node",
  },
  {
    id: "docker-compose",
    name: "Docker Compose (Multi-Container)",
    icon: "🐳",
    category: "docker",
    description: "Orchestrates multi-service apps via docker-compose.yml",
    defaultRootDirectory: "",
    installCommand: "docker compose build",
    buildCommand: "",
    startCommand: "docker compose up -d",
    defaultPort: 3000,
    healthCheckUrl: "/",
    processManager: "docker-compose",
  },
  {
    id: "dockerfile",
    name: "Docker Container (Dockerfile)",
    icon: "📦",
    category: "docker",
    description: "Builds and runs a standalone Docker image",
    defaultRootDirectory: "",
    installCommand: "",
    buildCommand: "docker build -t deploynest-app .",
    startCommand: "docker run -d --rm -p 3000:3000 --name deploynest-app deploynest-app",
    defaultPort: 3000,
    healthCheckUrl: "/",
    processManager: "docker",
  },
  {
    id: "static",
    name: "Static HTML / Client Web App",
    icon: "🌐",
    category: "static",
    description: "Pure HTML/CSS/JS or pre-built static directory",
    defaultRootDirectory: "",
    installCommand: "",
    buildCommand: "",
    startCommand: "npx serve -s . -l 3000",
    defaultPort: 3000,
    healthCheckUrl: "/",
    processManager: "node",
  },
  {
    id: "custom",
    name: "Custom / Generic Pipeline",
    icon: "⚙️",
    category: "other",
    description: "Custom user-defined build and run commands",
    defaultRootDirectory: "",
    installCommand: "npm install",
    buildCommand: "npm run build",
    startCommand: "npm start",
    defaultPort: 3000,
    healthCheckUrl: "/health",
    processManager: "custom",
  },
];
